### ISSUE TITLE
Design Social Media Interface

### ISSUE THREAD

**Issue by nathsoto1** [CSC-3380-Fall-2024/Team-16#2]
We need to design the social media interface for the fitness app, where users can post their workouts, food logs, and photos. This interface should also allow users to interact with friends and see their activity. The design should be user-friendly, visually appealing, and in line with the app's overall theme.

(still making edits, no one is allowed to assign this task)

**Comment by peterN12g** [comment]
![image](https://github.com/user-attachments/assets/472974ad-8af2-4eb0-a060-d137060056f7)
Rough figma design for social media pages
