### ISSUE TITLE
Design UI for Food Tracker

### ISSUE THREAD

**Issue by nathsoto1** [CSC-3380-Fall-2024/Team-16#3]
Design an intuitive and easy-to-use interface where users can log their daily meals. The food tracker should allow users to search for foods from a database, select portion sizes, and manually enter custom foods if needed. The goal is to make tracking meals quick and straightforward.

Requirements:
-Searchable database for logging foods.
-Option for manual entry of custom foods (e.g., homemade meals).
-Ability to adjust portion sizes, meal time, and food type.
-Clear input forms for ease of use, with intuitive navigation.
-Integration with the calorie counter to automatically update total daily intake.

Point value: 2

**Comment by peterN12g** [comment]
![Food Diary](https://github.com/user-attachments/assets/fd5e9961-79f7-49bc-8a52-71b9beb70380)


Food Diary Rough Figma Design

**Comment by peterN12g** [comment]
![image](https://github.com/user-attachments/assets/974b8aeb-f5ed-49af-bc41-463788c5deee)
Food diary rough Figma design
