### ISSUE TITLE
Design UI for Calorie Counter

### ISSUE THREAD

**Issue by nathsoto1** [CSC-3380-Fall-2024/Team-16#4]
Design an automatic calorie counter that calculates total daily calorie intake based on the foods logged by the user. This feature should visually display the calorie count and allow users to track their calorie intake versus their daily goals.

Requierments: 
-Display the total calories for each meal and the overall daily total.
-Show a progress bar or chart that compares calorie intake to the user’s daily goal.
-Provide a breakdown of calories by meal or food item.
-Integrate with the food tracker.

Point value: 2

**Comment by peterN12g** [comment]
![image](https://github.com/user-attachments/assets/a0f542ed-76bc-4931-9160-0f73e2e9007a)
Rough Figma Design
